version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  service1:
    build:
      context: ../front-proxy
      dockerfile: Dockerfile-service
    volumes:
      - ./service1-envoy-jaeger.yaml:/etc/service-envoy.yaml
      - ./libjaegertracing.so.0.4.2:/usr/local/lib/libjaegertracing_plugin.so
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  service2:
    build:
      context: ../front-proxy
      dockerfile: Dockerfile-service
    volumes:
      - ./service2-envoy-jaeger.yaml:/etc/service-envoy.yaml
      - ./libjaegertracing.so.0.4.2:/usr/local/lib/libjaegertracing_plugin.so
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  envoymesh: {}
